---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Kolkata
      - VERSION=docker
    volumes:
      - ./config:/config
      - /home/ubuntu/plex_media:/plex_media
    restart: no
